

controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_effort_controller:
      type: adog_legged_controller/AdogLeggedController
      
    leg_pd_controller:
      type: leg_pd_controller/LegPdController

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    fl_foot_force_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    fr_foot_force_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    rl_foot_force_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    rr_foot_force_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    ocs2_quadruped_controller:
      type: ocs2_quadruped_controller/Ocs2QuadrupedController

    # test_force_torque_sensor_broadcaster:
    #   ros__parameters:
    #     type: "force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster"
    #     frame_id: FL_foot
    #     sensor_name: ft_sensor
    #     update_rate: 50
    #     publish_rate: 50
fl_foot_force_sensor_broadcaster:
  ros__parameters:
    frame_id:  "FL_foot"
    sensor_name: "fl_ft_sensor"

fr_foot_force_sensor_broadcaster:
  ros__parameters:
    frame_id:  "FR_foot"
    sensor_name: "fr_ft_sensor"

rl_foot_force_sensor_broadcaster:
  ros__parameters:
    frame_id:  "RL_foot"
    sensor_name: "rl_ft_sensor"

rr_foot_force_sensor_broadcaster:
  ros__parameters:
    frame_id:  "RR_foot"
    sensor_name: "rr_ft_sensor"

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"

joint_effort_controller:
  ros__parameters:
    joints:
      - FL_hip_joint 
      - FL_thigh_joint 
      - FL_calf_joint 
 
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
 
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
 
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
    interface_name:
      - effort

leg_pd_controller:
  ros__parameters:
    update_rate: 1000  # Hz
    joints:
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint

    command_interfaces:
      - effort

    state_interfaces:
      - position
      - velocity

ocs2_quadruped_controller:
  ros__parameters:
    update_rate: 100  # Hz
    command_prefix: "leg_pd_controller"

    # urdf_file: "/home/ubuntu/adog_legged_control/install/go2_description/share/go2_description/urdf/robot.urdf"
    # task_file: "/home/ubuntu/adog_legged_control/install/go2_description/share/go2_description/config/ocs2/task.info"
    # reference_file: "/home/ubuntu/adog_legged_control/install/go2_description/share/go2_description/config/ocs2/reference.info"
    # gait_file: "/home/ubuntu/adog_legged_control/install/go2_description/share/go2_description/config/ocs2/gait.info"
    urdf_file: "/home/ubuntu/adog_legged_control/install/go2_description/share/go2_description/urdf/robot.urdf"
    task_file: "/home/ubuntu/adog_legged_control/install/unitree_go2_description/share/unitree_go2_description/config/ocs2/task.info"
    reference_file: "/home/ubuntu/adog_legged_control/install/unitree_go2_description/share/unitree_go2_description/config/ocs2/reference.info"
    gait_file: "/home/ubuntu/adog_legged_control/install/unitree_go2_description/share/unitree_go2_description/config/ocs2/gait.info"
    joints:
      - FL_hip_joint
      - FL_thigh_joint
      - FL_calf_joint
      - FR_hip_joint
      - FR_thigh_joint
      - FR_calf_joint
      - RL_hip_joint
      - RL_thigh_joint
      - RL_calf_joint
      - RR_hip_joint
      - RR_thigh_joint
      - RR_calf_joint

    command_interfaces:
      - effort #for gazebo
      - position
      - velocity
      - kp
      - kd

    state_interfaces:
      - effort
      - position
      - velocity

    feet:
      - FL_foot
      - FR_foot
      - RL_foot
      - RR_foot

    imu_name: "imu_sensor"
    base_name: "base"

    imu_interfaces:
      - orientation.w
      - orientation.x
      - orientation.y
      - orientation.z
      - angular_velocity.x
      - angular_velocity.y
      - angular_velocity.z
      - linear_acceleration.x
      - linear_acceleration.y
      - linear_acceleration.z

    foot_force_name: "foot_force"
    foot_force_interfaces:
       - FL
      # - RL
      # - FR
      # - RR


    
    