<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:macro name="leg" params="name mirror mirror_dae front_hind front_hind_dae">

        <joint name="${name}_hip_joint" type="revolute">
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${leg_offset_x} ${-leg_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                <origin rpy="0 0 0" xyz="${leg_offset_x} ${leg_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-leg_offset_x} ${-leg_offset_y} 0"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                <origin rpy="0 0 0" xyz="${-leg_offset_x} ${leg_offset_y} 0"/>
            </xacro:if>
            <parent link="trunk"/>
            <child link="${name}_hip"/>
            <axis xyz="1 0 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <xacro:if value="${(mirror_dae == True)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${hip_position_min}"
                       upper="${hip_position_max}"/>
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}" lower="${-hip_position_max}"
                       upper="${-hip_position_min}"/>
            </xacro:if>
        </joint>


        <link name="${name}_hip">
            <visual>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == True)}">
                    <origin rpy="0 ${PI} ${-PI/2}" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == True)}">
                    <origin rpy="${PI} ${PI} ${PI/2}" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == True) and (front_hind_dae == False)}">
                    <origin rpy="${PI} ${PI} ${-PI/2}" xyz="0 0 0"/>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False) and (front_hind_dae == False)}">
                    <origin rpy="0 ${PI} ${PI/2}" xyz="0 0 0"/>
                </xacro:if>
                <geometry>
                    <mesh filename="file://$(find adog_description)/meshes/link1.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 ${PI/2.0}" xyz="0 ${hip_offset*mirror} 0"/>
                <geometry>
                    <cylinder length="${hip_length}" radius="${hip_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x*front_hind} ${hip_com_y*mirror} ${hip_com_z}"/>
                <mass value="${hip_mass}"/>
                <inertia
                        ixx="${hip_ixx}" ixy="${hip_ixy*mirror*front_hind}" ixz="${hip_ixz*front_hind}"
                        iyy="${hip_iyy}" iyz="${hip_iyz*mirror}"
                        izz="${hip_izz}"/>
            </inertial>
        </link>

        <joint name="${name}_thigh_joint" type="revolute">
            <origin rpy="0 0 0" xyz="-0.00034926 ${thigh_offset*mirror} -0.011244"/>
            <parent link="${name}_hip"/>
            <child link="${name}_thigh"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}" lower="${thigh_position_min}"
                   upper="${thigh_position_max}"/>
        </joint>


      <link name="${name}_thigh">
    <visual>
        <!-- 处理旋转和位置变换 -->
        <xacro:if value="${mirror_dae == True}">
            <!-- 镜像翻转时，旋转 180° 或更改位置 -->
            <origin rpy="0 0 ${-PI/2}" xyz="0 0 0"/>
        </xacro:if>
        <xacro:if value="${mirror_dae == False}">
            <!-- 正常情况，无旋转或者根据需要微调位置 -->
            <origin rpy="0 0 ${-PI/2}" xyz="0 0 0"/>
        </xacro:if>
        <geometry>
            <xacro:if value="${mirror_dae == True}">
                <!-- 镜像模型 -->
                <mesh filename="file://$(find adog_description)/meshes/link2.STL" scale="-1 1 1"/>
            </xacro:if>
            <xacro:if value="${mirror_dae == False}">
                <!-- 正常模型 -->
                <mesh filename="file://$(find adog_description)/meshes/link2.STL" scale="1 1 1"/>
            </xacro:if>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${-thigh_length/2.0}"/>
                <geometry>
                    <box size="${thigh_length} ${thigh_width} ${thigh_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}"/>
                <mass value="${thigh_mass}"/>
                <inertia
                        ixx="${thigh_ixx}" ixy="${thigh_ixy*mirror}" ixz="${thigh_ixz}"
                        iyy="${thigh_iyy}" iyz="${thigh_iyz*mirror}"
                        izz="${thigh_izz}"/>
            </inertial>
        </link>


        <joint name="${name}_calf_joint" type="revolute">
            <origin rpy="${PI/2} ${PI} ${PI}" xyz="0 0 ${-thigh_length}"/>
            <parent link="${name}_thigh"/>
            <child link="${name}_calf"/>
            <axis xyz="0 1 0"/>
            <dynamics damping="${damping}" friction="${friction}"/>
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${calf_position_min}"
                   upper="${calf_position_max}" position="-0.5"/>
        </joint>


        <link name="${name}_calf">
            <visual>
                <origin rpy="0 ${PI/12} 0" xyz="0 0 0"/>
                <geometry>
                    <mesh filename="file://$(find adog_description)/meshes/link3.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 ${PI/2.0} 0" xyz="0 0 ${-calf_length/2.0}"/>
                <geometry>
                    <box size="${calf_length} ${calf_width} ${calf_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y} ${calf_com_z}"/>
                <mass value="${calf_mass}"/>
                <inertia
                        ixx="${calf_ixx}" ixy="${calf_ixy}" ixz="${calf_ixz}"
                        iyy="${calf_iyy}" iyz="${calf_iyz}"
                        izz="${calf_izz}"/>
            </inertial>
        </link>


        <joint name="${name}_foot_fixed" type="fixed">0
            <origin rpy="0 0 0" xyz="-0.045  -0.0 ${-(calf_length)}"/>
            <parent link="${name}_calf"/>
            <child link="${name}_foot"/>
        </joint>

        <link name="${name}_foot">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius-0.01}"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${foot_radius}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="${foot_mass}"/>
                <inertia
                        ixx="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" ixy="0.0" ixz="0.0"
                        iyy="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}" iyz="0.0"
                        izz="${(2*foot_mass)/5.0*(foot_radius*foot_radius)}"/>
            </inertial>
        </link>

        <joint name="${name}_wheel_joint" type="revolute">
    <origin rpy="0 ${PI/12} 0" xyz="-0.057 -0.020 ${-calf_length}"/>
    <parent link="${name}_calf"/>
    <child link="${name}_wheel_Link"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="${damping}" friction="${friction}"/>
    <limit effort="${wheel_torque_max}" velocity="${wheel_velocity_max}" lower="${wheel_position_min}"
           upper="${wheel_position_max}"/>
</joint>
 
 <link name="${name}_wheel_Link">
    <visual>
        <origin rpy="${PI/2} 0 ${PI/2}" xyz="0 0 0"/>
        <geometry>
            <mesh filename="file://$(find adog_description)/meshes/foot.STL" scale="0.001 0.001 0.001"/>
        </geometry>
    </visual>
    <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
            <mesh filename="file://$(find adog_description)/meshes/foot.STL" scale="0.001 0.001 0.001"/>
        </geometry>
    </collision>
    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
                ixx="${wheel_ixx}" ixy="${wheel_ixy}" ixz="${wheel_ixz}"
                iyy="${wheel_iyy}" iyz="${wheel_iyz}"
                izz="${wheel_izz}"/>
    </inertial>
</link>


        <!-- <xacro:adog_description name="${name}"/> -->
    </xacro:macro>
</robot>
