publisher_forward_position_controller:
  ros__parameters:

    controller_name: "joint_position_controller"
    wait_sec_between_publish: 2
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos1", "pos2", "pos3", "pos4"]
    pos1:  [0.0,0.0,0.0,0.0 ,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0]
    pos2:  [0.1,0.1,-0.1,-0.1 ,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0]
    pos3:  [0.0,0.0,0.0,0.0 ,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0]
    pos4:  [0.1,0.1,-0.1,-0.1 ,0.0,0.0,0.0,0.0, 0.0,0.0,0.0,0.0]

    joints:
      - FL_hip_joint 
      - FL_thigh_joint 
      - FL_calf_joint 
      - RL_hip_joint 
      - RL_thigh_joint 
      - RL_calf_joint 
      - FR_hip_joint 
      - FR_thigh_joint 
      - FR_calf_joint 
      - RR_hip_joint 
      - RR_thigh_joint 
      - RR_calf_joint 


    check_starting_point: false
    starting_point_limits:
      FL_hip_joint : [-0.1,0.1]
      FL_thigh_joint: [-0.1,0.1]
      FL_calf_joint : [-0.1,0.1]
      RL_hip_joint : [-0.1,0.1]
      RL_thigh_joint: [-0.1,0.1]
      RL_calf_joint : [-0.1,0.1]
      FR_hip_joint : [-0.1,0.1]
      FR_thigh_joint: [-0.1,0.1]
      FR_calf_joint : [-0.1,0.1]
      RR_hip_joint : [-0.1,0.1]
      RR_thigh_joint: [-0.1,0.1]
      RR_calf_joint : [-0.1,0.1]


